Fix #114 - return empty csv file (with headers) when no results.
moodleou/moodle-report_customsql pull request #122
Opened 2022-12-04 21:16 UTC by danmarsden

here's a method that allows us to use the plugins normal methods for printing columns in a report by adding a record of null values to the report when the main query is empty.

Hopefully it makes sense - seems to work cross db for me but would be good to test further - I'll see if we can get some other folks to test too.

2022-12-05 08:54 UTC, timhunt commented
Why do you want to do this? What have you done. Sure, I am capable of RTC, but it would be easier to review this request if you explain.

2022-12-05 09:47 UTC, danmarsden commented
Hey Tim, the 'reason' for this is covered in issue #114 is that what you're asking?

2022-12-05 10:16 UTC, timhunt commented
That is what I was asking.

I don't like the proposed fix.

I understand why you want to chagne the behaviour when used as a web service, but I don't think we should change other cases. Therefore, why not change just the web service code, and ensure the header row is always output in PHP, rather than messing with the SQL?

If this behaviour is important enough to implement, it is important enough to have an automated test.

Alos, not really your problem, but if you could add a separat commit to fix the CI build (I think it just needs a DB version bump) then that would save me time.

2022-12-05 18:03 UTC, danmarsden commented
Happy to look at adding tests, but..  any idea how to get the column names without using sql like this?  If the query is something like 'select * from {table}' we have to execute the sql to get the list of columns.. and moodle doesn't have a show columns type api that let's us get a list if columns based on some sql.. it has to return rows.

2022-12-05 18:18 UTC, timhunt commented
Oh yes. I was forgetting how this work. Too may things going on.

So, the issue is, if the report is being shown on-screen, we don't want the no rows behaviour to change. (Worth a Behat test to verify the current behaviour)

And, if this is a scheduled report, it is a feature that a file is only saved on disc if the report returned any data. 

So, we only want the 'create empty file' behaviour in the web service case (that is, when the call to report_customsql_generate_csv comes from report_customsql_pluginfile in lib.php).

I agree it is hard to work out how to test the download behaviour. Possibly a custom Behat step like `Then downloading customsql report "Query name" returns a file with headers "frog,toad"`. You can probably use behat_general::download_file_from_link to help implement that.

2022-12-06 23:02 UTC, timhunt commented
That is looking good now Dan. Just two minor quibbles which I would like to see fixed before I merge this.

2022-12-07 00:59 UTC, danmarsden commented
I assume you got a phonecall just after posting that... or you mean the missing behat tests? - or you have comments still in a draft form... or the quibbles are because you're reviewing code way too late in the night... :-)

2022-12-07 09:08 UTC, timhunt requested changes
I forgot that when you are making review commenst, you need to finish the review before the other person can see them.

Adding Behat tests also still desired. (Missing them was because it was late at night.)

2022-12-07 23:53 UTC, danmarsden commented on locallib.php
> +        }
yeah good call - I've added something along those lines now.

2022-12-07 23:54 UTC, danmarsden commented
thanks Tim - basic changes implemented - haven't managed to write behat tests yet but will try to find some time today/tomorrow to add some in...

2022-12-12 23:48 UTC, danmarsden commented
Hey Tim - I've just quickly dropped in a new behat test on that branch but I don't think the custom step is working quite right and I've obviously missed something/got a typo in there.... let me know if you spot the issue, otherwise I'll try to come back to this next week when I get some time.

2022-12-23 07:43 UTC, abias commented
Hi Tim, hi Dan,

I would like to quickly confirm that the current patch in this PR solves the issue which I reported in #114 successfully.

2023-01-09 22:21 UTC, danmarsden commented
Thanks @abias - @timhunt let me know if there's anything else you need here.

2023-02-06 16:52 UTC, abias commented
Hi @timhunt ,

we are eagerly waiting for this PR to land in an official release so we can use it in one of our instanced officially.
Is there any chance that you could have a final look and push this over the line?

Thanks in advance for your work!

2023-08-03 05:58 UTC, brendanheywood commented
hi @timhunt 

I've just tested this and it works great. The sql is weird but I can not see a better way of doing it without improving core, and I did propose this here but I still don't know how viable it is in every db driver:

https://tracker.moodle.org/browse/MDL-64387

Is there anything else blocking this from landing we can sort?

2023-12-13 12:52 UTC, closed without merging

2023-12-13 21:49 UTC, danmarsden commented
awesome - thanks heaps Tim! - hope you have a great break over Christmas! :-)

2024-04-17 06:33 UTC, abias commented
@timhunt - Many thanks for merging this PR!

Would you mind to push out a new release to https://moodle.org/plugins/report_customsql/versions which contains this fix as well? Our customer who paid for this fix prefers to install official releases.

Many thanks for your time!